package io.github.diskria.poetesse.java

import com.palantir.javapoet.ClassName
import com.palantir.javapoet.TypeSpec
import io.github.diskria.poetesse.Poetesse
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import javax.lang.model.element.Modifier

class MultiClassJavaDeferredFileTest {

    private val listType: ClassName = ClassName.get("java.util", "List")
    private val mapType: ClassName = ClassName.get("java.util", "Map")

    @Test
    fun `merges several types into a single file, preserving their order`() {
        val foo = publicClass("Foo")
        val bar = publicClass("Bar")

        val output = render(listOf(foo, bar))

        assertTrue(output.contains("class Foo"), output)
        assertTrue(output.contains("class Bar"), output)
        assertTrue(output.indexOf("class Foo") < output.indexOf("class Bar"), output)
    }

    @Test
    fun `writes the package declaration exactly once`() {
        val output = render(listOf(publicClass("Foo"), publicClass("Bar")))

        assertEquals(1, output.occurrencesOf("package com.example;"), output)
    }

    @Test
    fun `deduplicates imports shared between types`() {
        val foo = TypeSpec.classBuilder("Foo")
            .addModifiers(Modifier.PUBLIC)
            .addField(listType, "items", Modifier.PRIVATE)
            .build()
        val bar = TypeSpec.classBuilder("Bar")
            .addModifiers(Modifier.PUBLIC)
            .addField(listType, "keys", Modifier.PRIVATE) // same List import as Foo -> must collapse
            .addField(mapType, "cache", Modifier.PRIVATE)
            .build()

        val output = render(listOf(foo, bar))

        assertEquals(1, output.occurrencesOf("import java.util.List;"), output)
        assertEquals(1, output.occurrencesOf("import java.util.Map;"), output)
    }

    @Test
    fun `emits no import section when types need none`() {
        val output = render(listOf(publicClass("A"), publicClass("B")))

        assertEquals(0, output.occurrencesOf("import "), output)
    }

    @Test
    fun `prepends the comment header from settings`() {
        val output = render(
            listOf(publicClass("Foo")),
            settings = Poetesse.Settings(comment = "Generated by Poetesse"),
        )

        assertTrue(output.trimStart().startsWith("// Generated by Poetesse"), output)
    }

    private fun publicClass(name: String): TypeSpec =
        TypeSpec.classBuilder(name).addModifiers(Modifier.PUBLIC).build()

    private fun render(
        typeSpecs: List<TypeSpec>,
        settings: Poetesse.Settings = Poetesse.Settings(),
        packageName: String? = "com.example",
        fileName: String = typeSpecs.first().name(),
    ): String =
        buildString {
            MultiClassJavaDeferredFile.mergeFrom(packageName, fileName, typeSpecs, settings).writeTo(this)
        }

    private fun String.occurrencesOf(token: String): Int =
        split(token).size - 1
}
